### ISSUE TITLE
Building manipulated code under Windows server.

### ISSUE THREAD

**Issue by Arthur-Senior** [ungoogled-software/ungoogled-chromium#2904]
### OS/Platform

Windows

### Installed

Compiled from source

### Version

125

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

when i use the build.py to build original source it works, mostly. Sometimes i get error extension too long and mostly it stucked 

### How to Reproduce?

git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-windows.git
cd ungoogled-chromium-windows
# Replace TAG_OR_BRANCH_HERE with a tag or branch name
git checkout --recurse-submodules TAG_OR_BRANCH_HERE
python3 build.py

After this step build\src\third_party\ninja\ninja -C build\src\out\Default chrome

### Actual behaviour

tools/resources/generate_resource_allowlist.py -o gen/chrome/chrome_resource_allowlist.txt chrome.dll.pdb
Traceback (most recent call last):

stuckes on call "ninja -C out\Default chrome"

### Expected behaviour

building the files till end

### Relevant log output

```sh
FAILED: gen/chrome/chrome_resource_allowlist.txt
C:/Projects/depot_tools/bootstrap-2@3_11_8_chromium_35_bin/python3/bin/python3.exe ../../tools/resources/generate_resource_allowlist.py -o gen/chrome/chrome_resource_allowlist.txt chrome.dll.pdb
Traceback (most recent call last):
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 165, in <module>
    main()
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 161, in main
    WriteResourceAllowlist(args)
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 140, in WriteResourceAllowlist
    resource_ids.update(func(input))
                        ^^^^^^^^^^^
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 85, in GetResourceAllowlistPDB
    undname = subprocess.Popen(['undname', name],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\depot_tools\bootstrap-2@3_11_8_chromium_35_bin\python3\bin\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Projects\depot_tools\bootstrap-2@3_11_8_chromium_35_bin\python3\bin\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
ninja: build stopped: subcommand failed.
```

**Comment by PF4Public** [comment]
You seem to be missing `undname` utility on your system.

**Comment by PF4Public** [comment]
> Can you please send me the utility missing for my problem please?

I don't have Windows at hand, so cannot advise you on that.

**Comment by Arthur-Senior** [comment]
Already working. Compiling first patches

сб, 8 июн. 2024 г., 17:35 PF4Public ***@***.***>:

**Comment by PF4Public** [comment]
I'll close this issue then.

**Comment by Arthur-Senior** [comment]
no i get the following error: 
i.c updater_legacy_idl_p.c ../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe gen/chrome/updater/app/server/win/updater_legacy_idl.template /char signed /env x64 /Oicf
Traceback (most recent call last):
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 459, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 399, in main
    overwrite_guids(*(os.path.join(outdir, file) if file else None
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 237, in overwrite_guids
    overwrite_guids_tlb(tlb_file, dynamic_guids)
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 199, in overwrite_guids_tlb
    contents, ntypes, type_off, guid_off, guid_len = get_tlb_contents(tlb_file)
  File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 104, in get_tlb_contents
    assert contents[0:8] == b'MSFT\x02\x00\x01\x00'
AssertionError
