### ISSUE TITLE
ChatGPT scroll worked in 128 but not in 130

### ISSUE THREAD

**Issue by arteze** [ungoogled-software/ungoogled-chromium#3111]
### OS/Platform

Other Linux (please specify)

### Installed

OS/Platform's package manager

### Version

Versión 128.0.6613.137 (Official Build, ungoogled-chromium) openmandriva 24.90 (64 bits)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

ChatGPT is not working

### How to Reproduce?

1. Log in to ChatGPT: https://chatgpt.com/
2. Write something
3. Press Enter
4. Press the button to send something

### Actual behaviour

ChatGPT doesn't work, I get errors like this.
```js
/backend-api/accounts/check/v4-2023-04-27?timezone_offset_min=180:1 
        
       Failed to load resource: the server responded with a status of 403 ()
```

### Expected behaviour

That ChatGPT works, that you can send messages and it responds.

### Relevant log output

```sh
Errors in the development console:

Failed to load resource: the server responded with a status of 403 ()
es3j5ln8se5pxxw4.js:1 Intercom not booted or setup incomplete.
o @ es3j5ln8se5pxxw4.js:1
we @ es3j5ln8se5pxxw4.js:1
(anonymous) @ gfs0keudzvcg5rgq.js:267
/backend-api/accounts/check/v4-2023-04-27?timezone_offset_min=180:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
es3j5ln8se5pxxw4.js:1 Intercom not booted or setup incomplete.
o @ es3j5ln8se5pxxw4.js:1
we @ es3j5ln8se5pxxw4.js:1
(anonymous) @ gfs0keudzvcg5rgq.js:267
es3j5ln8se5pxxw4.js:1 Intercom not booted or setup incomplete.
o @ es3j5ln8se5pxxw4.js:1
re @ es3j5ln8se5pxxw4.js:1
(anonymous) @ gfs0keudzvcg5rgq.js:267
/ces/v1/projects/oai/settings:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
gfs0keudzvcg5rgq.js:218 <html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;flex-direction:column;gap:2rem;height:100%;justify-content:center;width:100%}@keyframes enlarge-appear{0%{opacity:0;transform:scale(75%) rotate(-90deg)}to{opacity:1;transform:scale(100%) rotate(0deg)}}.logo{color:#8e8ea0}.scale-appear{animation:enlarge-appear .4s ease-out}@media (min-width:768px){.scale-appear{height:48px;width:48px}}.data:empty{display:none}.data{border-radius:5px;color:#8e8ea0;text-align:center}@media (prefers-color-scheme:dark){body{background-color:#343541}.logo{color:#acacbe}}</style>
  <meta http-equiv="refresh" content="390">
</head>
  <body>
    <div class="container">
      <div class="logo">
        <svg
          width="41"
          height="41"
          viewBox="0 0 41 41"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          strokeWidth="2"
          class="scale-appear"
        >
          <path
            d="M37.5324 16.8707C37.9808 15.5241 38.1363 14.0974 37.9886 12.6859C37.8409 11.2744 37.3934 9.91076 36.676 8.68622C35.6126 6.83404 33.9882 5.3676 32.0373 4.4985C30.0864 3.62941 27.9098 3.40259 25.8215 3.85078C24.8796 2.7893 23.7219 1.94125 22.4257 1.36341C21.1295 0.785575 19.7249 0.491269 18.3058 0.500197C16.1708 0.495044 14.0893 1.16803 12.3614 2.42214C10.6335 3.67624 9.34853 5.44666 8.6917 7.47815C7.30085 7.76286 5.98686 8.3414 4.8377 9.17505C3.68854 10.0087 2.73073 11.0782 2.02839 12.312C0.956464 14.1591 0.498905 16.2988 0.721698 18.4228C0.944492 20.5467 1.83612 22.5449 3.268 24.1293C2.81966 25.4759 2.66413 26.9026 2.81182 28.3141C2.95951 29.7256 3.40701 31.0892 4.12437 32.3138C5.18791 34.1659 6.8123 35.6322 8.76321 36.5013C10.7141 37.3704 12.8907 37.5973 14.9789 37.1492C15.9208 38.2107 17.0786 39.0587 18.3747 39.6366C19.6709 40.2144 21.0755 40.5087 22.4946 40.4998C24.6307 40.5054 26.7133 39.8321 28.4418 38.5772C30.1704 37.3223 31.4556 35.5506 32.1119 33.5179C33.5027 33.2332 34.8167 32.6547 35.9659 31.821C37.115 30.9874 38.0728 29.9178 38.7752 28.684C39.8458 26.8371 40.3023 24.6979 40.0789 22.5748C39.8556 20.4517 38.9639 18.4544 37.5324 16.8707ZM22.4978 37.8849C20.7443 37.8874 19.0459 37.2733 17.6994 36.1501C17.7601 36.117 17.8666 36.0586 17.936 36.0161L25.9004 31.4156C26.1003 31.3019 26.2663 31.137 26.3813 30.9378C26.4964 30.7386 26.5563 30.5124 26.5549 30.2825V19.0542L29.9213 20.998C29.9389 21.0068 29.9541 21.0198 29.9656 21.0359C29.977 21.052 29.9842 21.0707 29.9867 21.0902V30.3889C29.9842 32.375 29.1946 34.2791 27.7909 35.6841C26.3872 37.0892 24.4838 37.8806 22.4978 37.8849ZM6.39227 31.0064C5.51397 29.4888 5.19742 27.7107 5.49804 25.9832C5.55718 26.0187 5.66048 26.0818 5.73461 26.1244L13.699 30.7248C13.8975 30.8408 14.1233 30.902 14.3532 30.902C14.583 30.902 14.8088 30.8408 15.0073 30.7248L24.731 25.1103V28.9979C24.7321 29.0177 24.7283 29.0376 24.7199 29.0556C24.7115 29.0736 24.6988 29.0893 24.6829 29.1012L16.6317 33.7497C14.9096 34.7416 12.8643 35.0097 10.9447 34.4954C9.02506 33.9811 7.38785 32.7263 6.39227 31.0064ZM4.29707 13.6194C5.17156 12.0998 6.55279 10.9364 8.19885 10.3327C8.19885 10.4013 8.19491 10.5228 8.19491 10.6071V19.808C8.19351 20.0378 8.25334 20.2638 8.36823 20.4629C8.48312 20.6619 8.64893 20.8267 8.84863 20.9404L18.5723 26.5542L15.206 28.4979C15.1894 28.5089 15.1703 28.5155 15.1505 28.5173C15.1307 28.5191 15.1107 28.516 15.0924 28.5082L7.04046 23.8557C5.32135 22.8601 4.06716 21.2235 3.55289 19.3046C3.03862 17.3858 3.30624 15.3413 4.29707 13.6194ZM31.955 20.0556L22.2312 14.4411L25.5976 12.4981C25.6142 12.4872 25.6333 12.4805 25.6531 12.4787C25.6729 12.4769 25.6928 12.4801 25.7111 12.4879L33.7631 17.1364C34.9967 17.849 36.0017 18.8982 36.6606 20.1613C37.3194 21.4244 37.6047 22.849 37.4832 24.2684C37.3617 25.6878 36.8382 27.0432 35.9743 28.1759C35.1103 29.3086 33.9415 30.1717 32.6047 30.6641C32.6047 30.5947 32.6047 30.4733 32.6047 30.3889V21.188C32.6066 20.9586 32.5474 20.7328 32.4332 20.5338C32.319 20.3348 32.154 20.1698 31.955 20.0556ZM35.3055 15.0128C35.2464 14.9765 35.1431 14.9142 35.069 14.8717L27.1045 10.2712C26.906 10.1554 26.6803 10.0943 26.4504 10.0943C26.2206 10.0943 25.9948 10.1554 25.7963 10.2712L16.0726 15.8858V11.9982C16.0715 11.9783 16.0753 11.9585 16.0837 11.9405C16.0921 11.9225 16.1048 11.9068 16.1207 11.8949L24.1719 7.25025C25.4053 6.53903 26.8158 6.19376 28.2383 6.25482C29.6608 6.31589 31.0364 6.78077 32.2044 7.59508C33.3723 8.40939 34.2842 9.53945 34.8334 10.8531C35.3826 12.1667 35.5464 13.6095 35.3055 15.0128ZM14.2424 21.9419L10.8752 19.9981C10.8576 19.9893 10.8423 19.9763 10.8309 19.9602C10.8195 19.9441 10.8122 19.9254 10.8098 19.9058V10.6071C10.8107 9.18295 11.2173 7.78848 11.9819 6.58696C12.7466 5.38544 13.8377 4.42659 15.1275 3.82264C16.4173 3.21869 17.8524 2.99464 19.2649 3.1767C20.6775 3.35876 22.0089 3.93941 23.1034 4.85067C23.0427 4.88379 22.937 4.94215 22.8668 4.98473L14.9024 9.58517C14.7025 9.69878 14.5366 9
Bn.<computed> @ gfs0keudzvcg5rgq.js:218
(anonymous) @ oavbr74nzqxxi24p.js:2
/backend-api/conversations?offset=0&limit=28&order=updated:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
es3j5ln8se5pxxw4.js:1 Intercom not booted or setup incomplete.
o @ es3j5ln8se5pxxw4.js:1
we @ es3j5ln8se5pxxw4.js:1
(anonymous) @ gfs0keudzvcg5rgq.js:267
/backend-api/models?history_and_training_disabled=false:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/prompt_library/?limit=4&offset=0:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/prompt_library/?limit=8&offset=0&use_v2=true&model_slug=gpt-4o-mini:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/prompt_library/?limit=4&offset=0&model_slug=gpt-4o-mini:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/conversation/init:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/sentinel/chat-requirements:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/models?history_and_training_disabled=false:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
5gfs0keudzvcg5rgq.js:267 Uncaught (in promise) RequestError: Something went wrong. If this issue persists please contact us through our help center at help.openai.com.
    at br.fetch (gfs0keudzvcg5rgq.js:267:23754)
fetch @ gfs0keudzvcg5rgq.js:267
dv7yn9no9p7iay99.js:3 Uncaught (in promise) RequestError: Something went wrong. If this issue persists please contact us through our help center at help.openai.com.
    at br.fetch (gfs0keudzvcg5rgq.js:267:23754)
fetch @ gfs0keudzvcg5rgq.js:267
/backend-api/conversation/init:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/conversations?offset=0&limit=28&order=updated:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
es3j5ln8se5pxxw4.js:1 Intercom not booted or setup incomplete.
o @ es3j5ln8se5pxxw4.js:1
we @ es3j5ln8se5pxxw4.js:1
(anonymous) @ gfs0keudzvcg5rgq.js:267
/backend-api/conversation/init:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/backend-api/conversation/init:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
```

### Additional context

Photo of ChatGPT not working on my computer (in Spanish):
![c(40)](https://github.com/user-attachments/assets/ec52d34b-822c-4c04-8b1f-2e5f47663f5a)

**Comment by arteze** [comment]
It's already fixed, I think it's because the CPU temperature was at 100 degrees Celsius and that's why it didn't have time to load the JS libraries.

**Comment by arteze** [comment]
What I do have a problem with is that I can't scroll using the arrow keys. Why is that? I thought that with the updated browser it wouldn't happen, but it keeps happening.

**Comment by arteze** [comment]
I found a partial solution to the scrolling problem.

1. Click on the box to send a message.
2. Press Shift + Tab, this will select the options at the end of the message that ChatGPT responded to.
3. Press Tab 5 more times without releasing Shift. This will bring up the share button.
4. Scrolling with Page Down, this works. It doesn't work with the arrow keys.

**Comment by arteze** [comment]
I've already found the definitive solution to scrolling:
1. Go to `chrome://flags/`
2. Set to Enabled: `Enables keyboard focusable scrollers`

**Comment by arteze** [comment]
I just updated from _Chromium 128_ to _Chromium 130_, and when I put the parameter `--gtk-version=4` it still looks like I have _GTK3_, and the _Spanish accents_ don't even work anymore (the problem I had before), and now the _ChatGPT scroll_ doesn't work either, _even if focusable scrollers are enabled_.

**Comment by arteze** [comment]
#!/bin/sh

busybox rm -v /usr/lib/chromium/*.so.*
ln -svfr /usr/lib/libGLESv2.so.2.1.0 /usr/lib/chromium/libGLESv2.so
ln -svfr /usr/lib/libEGL.so.1 /usr/lib/chromium/libEGL.so

----

I managed to fix the Spanish accents problem by making it load GTK4 from the system libraries. Before it used the ones in `/usr/lib/chromium`, so I deleted the `.so` files in that folder, then linked `libEGL.so` and `libGLESv2.so` to the system libraries because it said they were missing.
```sh
busybox rm -v /usr/lib/chromium/*.so.*
ln -svfr /usr/lib/libGLESv2.so.2.1.0 /usr/lib/chromium/libGLESv2.so
ln -svfr /usr/lib/libEGL.so.1 /usr/lib/chromium/libEGL.so
```

I tried changing some options in `chrome://flags`, but the ChatGPT scrolling issue still persists.

**Comment by arteze** [comment]
I downloaded several versions from the website and I could see that in 131 and 130 the scroll does not work.

In version 129 it works perfectly.
- https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/129.0.6668.100-1

![c(42)](https://github.com/user-attachments/assets/3680a1e5-6456-4d64-8d77-8efe8cc752ef)

**Comment by arteze** [comment]
I was able to verify that in version _126.0.6478.55_ the ChatGPT scroll works well, with the focusable flag activated.

I also just discovered which line was preventing GTK4 from loading.

__/opt/chromium/chrome-wrapper__
```sh
# Always use our ffmpeg and other shared libs.
# export LD_LIBRARY_PATH="$HERE:$HERE/lib:$HERE/lib.target${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
```
Commenting out the line with `#` solves the problem. And you also need to pass the parameter `--gtk-version=4` for it to work.

**Comment by arteze** [comment]
I asked ChatGPT for a Tampermonkey extension to fix the scrolling on older versions, and it works perfectly.

Simplified code:
```js
function focusable_scroll(){
	document.querySelectorAll('*').map(x=>{
		( x.scrollHeight > x.clientHeight
			|| x.scrollWidth > x.clientWidth
				&& ['auto', 'scroll'].includes(getComputedStyle(x).overflow)
			|| ['auto', 'scroll'].includes(getComputedStyle(x).overflowY)
			|| ['auto', 'scroll'].includes(getComputedStyle(x).overflowX)
		) && !x.hasAttribute('tabindex') && x.setAttribute('tabindex', '0')
			|| x.hasAttribute('tabindex') && x.removeAttribute('tabindex')
	})
}
var observer = new MutationObserver(()=>focusable_scroll())
observer.observe( document.body ,{ childList: true, subtree: true })
focusable_scroll()
```
